# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: |
    (?x)^(
        InvenTree/InvenTree/static/.*|
        InvenTree/locale/.*
    )$
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: mixed-line-ending
-   repo: https://github.com/pycqa/flake8
    rev: '6.0.0'
    hooks:
    -   id: flake8
        additional_dependencies: [
                'flake8-bugbear',
                'flake8-comprehensions',
                'flake8-docstrings',
                'flake8-string-format',
                'flake8-tidy-imports',
                'pep8-naming'
        ]
-   repo: https://github.com/pycqa/isort
    rev: '5.12.0'
    hooks:
    -   id: isort
-   repo: https://github.com/jazzband/pip-tools
    rev: 6.13.0
    hooks:
      - id: pip-compile
        name: pip-compile requirements-dev.in
        args: [requirements-dev.in, -o, requirements-dev.txt]
        files: ^requirements-dev\.(in|txt)$
      - id: pip-compile
        name: pip-compile requirements.txt
        args: [requirements.in, -o, requirements.txt]
        files: ^requirements\.(in|txt)$
-   repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.29.0
    hooks:
      - id: djlint-django
